#!/bin/bash

#-----------------------------------------------
#Updates versions for all onos cord applications
#-----------------------------------------------

APP_VERSION=$1
ONOS_VERSION=$2

cd apps

mvn -U versions:set -DallowSnapshots=true -DnewVersion=$APP_VERSION versions:commit
git submodule foreach mvn -U versions:set -DallowSnapshots=true -DnewVersion=$APP_VERSION versions:commit


git submodule foreach mvn -U versions:update-parent -DallowSnapshots=true -DparentVersion=[$ONOS_VERSION] versions:commit
git submodule foreach mvn -U versions:update-property -Dproperty=onos.version -DnewVersion=[$ONOS_VERSION] -DallowSnapshots=true versions:commit
