- name: Install compose for mavenrepo
  become: yes
  template:
    src: templates/{{ item }}.j2
    dest: /etc/maas/{{ item }}
    owner: maas
    group: maas
    mode: 0644
  with_items:
    - mavenrepo.yml
  tags: [repo]

- name: Ensure mavenrepo Running
  become: yes
  command: docker-compose -f /etc/maas/{{ item }} up -d
  with_items:
    - mavenrepo.yml
  tags: [repo]
